### ISSUE TITLE
LT#1 - Goでリアルタイム通信ゲームサーバーを作っている話

### ISSUE THREAD

**Issue by yhirano55** [server-side-shinjuku/meetups#1]
:warning: 注意事項

:one: 質問は 👇 のコメントフォームにてご投稿ください。
:two: 投稿順に回答していきます。
:three: 予定時刻に達したら質疑応答は終了しますのでご了承ください:bow:

**Comment by 284km** [comment]
API server では Rails、マッチング  server では Go とそれぞれ別の選択をしたのは、どの様な理由があるでしょうか。

**Comment by tikasan** [comment]
rakeでビルドしていましたが、普通にビルド走らせるとの違いはなんでしょうか。

**Comment by shiwano** [comment]
@284km Go で常時接続サーバーとして実装したら、マッチングしているかどうかの状態を、サーバーに接続しているかどうかで判定できるので、バグなく簡単に実装できそうだなと思ったのが理由でしょうか。Rails でも実装できるとは思いますし、そんなに深い理由はないです…！

**Comment by shiwano** [comment]
@tikasan https://github.com/shiwano/submarine
コードは上記 URL で見れます…！

https://github.com/shiwano/submarine/blob/master/server/battle/Rakefile
`rake build` は今のところ `go build` しているだけです。デバッグ用のビルドのフラグを覚えるのがめんどくさくて、Rakefile 書いてたんですが、将来的にはアセットのビルドとかも一緒に実行できたらいいかなーと思ってます

**Comment by 284km** [comment]
@shiwano ありがとうございます！
