### ISSUE TITLE
LT#2 - 犬でもできる！疑似生体SSH認証！

### ISSUE THREAD

**Issue by yhirano55** [server-side-shinjuku/meetups#2]
:warning: 注意事項

:one: 質問は 👇 のコメントフォームにてご投稿ください。
:two: 投稿順に回答していきます。
:three: 予定時刻に達したら質疑応答は終了しますのでご了承ください:bow:

**Comment by KeisukeUtsumi** [comment]
⚠️ 注意事項
埋め込み方や、どこで出来るのか、などの質問はお答えしませんのでご了承ください。
お察しください。

**Comment by dnond** [comment]
デモが分からなかったので、動画をあっぷして欲しいです！

**Comment by yhirano55** [comment]
ファミリーに怒られませんでしたか？

**Comment by KeisukeUtsumi** [comment]
https://twitter.com/voidofglans/status/852484914599428096

動画Twitterでupしました！
