### ISSUE TITLE
LT#3 - goパッケージで型情報を用いたソースコード検索を実現する

### ISSUE THREAD

**Issue by yhirano55** [server-side-shinjuku/meetups#3]
:warning: 注意事項

:one: 質問は 👇 のコメントフォームにてご投稿ください。
:two: 投稿順に回答していきます。
:three: 予定時刻に達したら質疑応答は終了しますのでご了承ください:bow:

**Comment by hatajoe** [comment]
内容とは違うんですが、DEMOで使ってる謎ツールがすごく便利そうで気になりました。

**Comment by decafe09** [comment]
これだと思います。 https://github.com/adg/dt
